version: "3.8"

services:
  db:
    image: mysql:8
    container_name: db_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 5
      timeout: 5s

  django_app:
    build:
      context: .
    image: notes-app
    container_name: django_cont
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
      - notes-net

  nginx:
    build: ./nginx
    image: nginx:latest
    container_name: nginx_cont
    ports:
      - "80:80"
    depends_on:
      - django_app
    networks:
      - notes-net

volumes:
  db_data:

networks:
  notes-net:
